server:
  port: 8000
  forward-headers-strategy: native
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always

  shardingsphere:
    orchestration:
      name: test
      overwrite: false
      registry:
        type: zookeeper
        server-lists: localhost:2181
        namespace: test

  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    run.acm.app: INFO
  file:
    path: ${user.home}/.acm/logs